magic_quotes_gpc = Off
memory_limit = 2048M
safe_mode = Off
display_errors = Off
upload_max_filesize = 2048M
allow_url_fopen = On
post_max_size = 2048M
max_input_vars = 3000
max_execution_time = 3000

